#!/bin/bash
reposDir='repos-final'
pathDir='final_repos'
for ext in asm ada erlang fortran haskell lisp lua matlab newlisp octave pl sml java py
#rb c c++
#c c++
#lua matlab newlisp octave pl php 
#fortran haskell lisp 
#
# asm ada erlang 
#c c++ py rb
#java
#ada
#asm c c++ erlang fortran haskell lisp java lua matlab newlisp octave pl py php rb sml
do
    if [ ! -d ${reposDir}-$ext ]
    then
        mkdir ${reposDir}-$ext
    fi
    echo .$ext
#    echo "python corpus_token.py ~/wxmao/umass/research/software/repository/repos_path/${ext}_Path repos-$ext/corpus_token-seperateStr repos-$ext/file_token-seperateStr > repos-$ext/heap_law &"
    
    
########################################################################################################
######
###### parsing with self-written parser, ignore sematic
#    python corpus_parser.py ~/wxmao/umass/research/software/repository/${pathDir}/${ext}_Path ${reposDir}-$ext/corpus_token ${reposDir}-$ext/file_token &
#    python corpus_parser.py -i ~/wxmao/umass/research/software/repository/${pathDir}/${ext}_Path -o ${reposDir}-$ext -f -h -t 1000000 > ${reposDir}-$ext/heap_law &
######
######
########################################################################################################
    
#    awk '{if($1~/^Token/)print $1}' $reposDir-$ext/token_dict_pygments | sort -u > $reposDir-$ext/token_pygments_type &

# > ${pathDir}-$ext/heap_law &
#echo "python parser_with_pygments.py $ext ~/wxmao/umass/research/software/repository/repos_path/${ext}_Path > repos-$ext/toke_type &"

########################################################################################################
######
######  parsing with pygments, outputing tokens generated by pygments(sematic involving)
#    python parser_with_pygments.py -l $ext -i ~/wxmao/umass/research/software/repository/${pathDir}/${ext}_Path -o ${reposDir}-$ext -h -t 1000000 &
    python parser_with_pygments.py -l $ext -i ~/wxmao/umass/research/software/repository/${pathDir}/${ext}_Path -o ${reposDir}-$ext -f &
#   for n in 1 2 3
#    do
#        python parser_with_pygments.py -l $ext -i ~/wxmao/umass/research/software/repository/${pathDir}/${ext}_Path -o ${reposDir}-$ext -n $n -f -h -t 1000000 &
#    done
######
######
########################################################################################################    
#    if [ -f ${reposDir}-$ext/toke_dict_pygments ];
#    then
#        echo ${reposDir}-$ext/toke_dict_pygments
#        python parser_with_pygments.py ${reposDir}-$ext/toke_dict_pygments > ${reposDir}-$ext/token_dict_pygments_name &
#    fi
#    python corpus_parser.py .$ext ../../repository/github-repository repos-$ext/corpus_token-seperateStr repos-$ext/file_token-seperateStr > repos-$ext/heap_law &
done
